DROP TABLE KOREABIKE;

CREATE TABLE KOREABIKE(
	NAME VARCHAR2(1000) NOT NULL,
	ADDR VARCHAR2(2000) NOT NULL,
	LATITUDE NUMBER NOT NULL,
	LONGITUDE NUMBER NOT NULL,
	BIKE_COUNT NUMBER NOT NULL
);


select * from koreabike;

truncate table KOREABIKE;

select count(*) from koreabike;